config/routes.rb
Rails.application.routes.draw do
    root "users#index"

    resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
    belongs_to :user
    validates :content, length: {maximum: 140},
                        presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts
    validates :name, presence: true 
    validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
    
        if @user.save
          redirect_to @user
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])

        if @user.update(user_params)
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
    
        redirect_to root_path, status: :see_other
    end

    private
        def user_params
            params.require(:user).permit(:name, :email)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toy App No Scaffold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header><h1>Toy App</h1></header>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
        <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<%= link_to "New User", new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<p><%= @user.name %></p>

<p><%= @user.email %></p>

<ul>
  <li><%= link_to "Edit", edit_user_path(@user) %></li>
  <li><%= link_to "Destroy", user_path(@user), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></li>
</ul>